#!/bin/bash

CONFIG_FILE='/etc/ebtables.conf'

case $1 in
  start)
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 35.190.247.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 35.190.247.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 35.191.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 64.233.160.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 66.102.0.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 66.249.80.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 72.14.192.0/18 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 74.125.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 108.177.8.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 108.177.96.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 130.211.0.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 172.217.0.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 172.217.128.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 172.217.160.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 172.217.192.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 172.217.32.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 173.194.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 209.85.128.0/17 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 216.239.32.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 216.58.192.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 31.13.24.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 31.13.64.0/18 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 45.64.40.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 66.220.144.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 69.63.176.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 69.171.224.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 74.119.76.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.4.96.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 129.134.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 157.240.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 173.252.64.0/18 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 179.60.192.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 185.60.216.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 204.15.20.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 69.12.56.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.252.112.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 104.244.40.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 185.45.4.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 188.64.224.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 192.44.68.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 192.48.236.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 192.133.76.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.16.156.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.59.148.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.69.58.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.96.56.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 202.160.128.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 45.58.64.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 108.160.160.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 162.125.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 185.45.8.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.47.216.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 67.199.248.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.2.28.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.2.30.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 119.235.224.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 147.92.128.0/17 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 203.104.128.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 203.104.144.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 203.104.152.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 203.104.156.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 203.104.158.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 23.185.0.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 23.235.32.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 43.249.72.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 63.211.233.2/32 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.244.50.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.245.222.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.245.224.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 104.156.80.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 151.101.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 157.52.64.0/18 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 172.111.64.0/18 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 185.31.16.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.27.72.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 199.232.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.4.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.8.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.12.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.16.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.20.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.36.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.38.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.108.56.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 149.154.160.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 149.154.164.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 149.154.168.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 149.154.172.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.0.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.32.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.39.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.40.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.48.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.64.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.80.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.88.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.92.248.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.128.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.136.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.138.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.142.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.144.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.148.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.150.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.154.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.156.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.163.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.164.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.168.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.172.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.95.174.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.216.0.0/15 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.218.0.0/16 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.0.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.32.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.56.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.64.0/19 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.96.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.112.0/21 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 52.219.120.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.0.0/17 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.128.0/18 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.192.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.224.0/20 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.240.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.248.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 54.231.252.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 66.6.32.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 141.193.88.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 192.34.198.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 192.94.66.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 198.187.223.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 61.204.150.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 202.219.104.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 202.248.110.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 202.248.252.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 91.198.174.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 103.102.166.0/24 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 185.15.56.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 198.35.26.0/23 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 208.80.152.0/22 -j redirect --redirect-target ACCEPT
    ebtables -t nat -A PREROUTING --logical-in br0 -p ipv4 --ip-dst 208.67.222.0/24 -j redirect --redirect-target ACCEPT
  ;;
  stop)
    ebtables -F
    ebtables -t nat -F
  ;;
  save)
    ebtables-save > "$CONFIG_FILE"
  ;;
  *)
    echo "usage: ${0##*/} {start|stop|save}" >&2
    exit 1
  ;;
esac

# vim:set ts=2 sw=2 ft=sh et:
